import {UNITS,US_CUP,number,convert,decimal,amountText,measured,practical,buildDough,analyseDough,panScale,oven,scaleAmount} from './math.mjs';
import {INGREDIENTS,ingredient} from './ingredients.mjs';
import {getRecipes,putRecipe,deleteRecipe,migrate,validateBackup,importRecipes} from './storage.mjs';
const $=id=>document.getElementById(id),state={ingredient:'all_purpose_flour',conversion:null,recipes:[],editing:null,photo:null,detail:null,mode:'build',sourdough:false};
let toastTimer,previewURL,detailURL,listURLs=[];
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(message){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast')?.classList.remove('visible'),4500);}
function errorAt(id,message){const e=$(id);e.textContent=message||'';e.hidden=!message;}
function showDialog(id){$(id).showModal();}
for(const b of document.querySelectorAll('[data-close]'))b.addEventListener('click',()=>b.closest('dialog').close());
for(const dialog of document.querySelectorAll('dialog'))dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
function switchView(id){for(const view of document.querySelectorAll('.view'))view.hidden=view.id!==id;for(const b of document.querySelectorAll('nav button')){if(b.dataset.view===id)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');}if(id==='recipes')renderRecipes();window.scrollTo({top:0});}
for(const b of document.querySelectorAll('nav button'))b.onclick=()=>switchView(b.dataset.view);
function unitOptions(selected='g'){return Object.entries(UNITS).map(([id,u])=>`<option value="${id}" ${selected===id?'selected':''}>${u.label}</option>`).join('');}
$('from-unit').innerHTML=unitOptions('g');$('to-unit').innerHTML=unitOptions('cup');
function normaliseGrams(input){
 const text=input.value.trim().replace(',','.');
 if(/^\d+\.\d+$/.test(text)&&Number.isFinite(Number(text))){input.value=String(Math.trunc(Number(text)));toast('Grams use whole numbers. The decimal part was removed.');}
 input.inputMode='numeric';input.setAttribute('pattern','[0-9]*');
}
function bindGramInputs(root=document){for(const input of root.querySelectorAll('[data-grams]')){input.addEventListener('blur',()=>{normaliseGrams(input);input.dispatchEvent(new Event('input',{bubbles:true}));});input.inputMode='numeric';}}
function syncFrom(normalise=true){if($('from-unit').value==='g'){if(normalise)normaliseGrams($('amount'));else $('amount').inputMode='numeric';}else{$('amount').inputMode='decimal';$('amount').removeAttribute('pattern');}}
function renderConversion(){
 const ing=ingredient(state.ingredient);$('ingredient-name').textContent=ing.name;$('ingredient-alias').textContent=ing.aliases||'Baking ingredient';
 try{const from=$('from-unit').value,to=$('to-unit').value,v=number($('amount').value,{whole:from==='g'}),result=convert(v,from,to,ing),ml=convert(v,from,'ml',ing);state.conversion={result,from,to};
  const rounded=to==='g'&&result>=.5&&Math.abs(result-Math.round(result))>1e-8;
  $('result').textContent=(rounded?'≈ ':'')+amountText(result,to);
  const metric=['metric_cup','metric_tbsp','metric_tsp','ml','l'].includes(to);
  $('practical').textContent=practical(ml,metric);$('practical-system').textContent=metric?'Metric cup 250 mL · tbsp 15 mL · tsp 5 mL':'US cup · 16 tablespoons or 48 teaspoons';
  $('conversion-note').textContent=to==='g'?'Gram results are rounded to whole grams. “<1” means less than one gram.':UNITS[from].kind!==UNITS[to].kind?'Uses an ingredient-specific reference. Volume measurements vary with filling and packing.':'';
  errorAt('convert-error','');
 }catch(e){state.conversion=null;$('result').textContent='—';$('practical').textContent='—';$('practical-system').textContent='';$('conversion-note').textContent='';errorAt('convert-error',e.message);}
}
$('amount').oninput=()=>{syncFrom(false);renderConversion();};$('amount').onblur=()=>{syncFrom();renderConversion();};$('from-unit').onchange=()=>{syncFrom();renderConversion();};$('to-unit').onchange=renderConversion;
$('swap').onclick=()=>{if(!state.conversion)return;const {result,from,to}=state.conversion;$('from-unit').value=to;$('to-unit').value=from;$('amount').value=to==='g'?String(Math.round(result)):decimal(result,12);syncFrom();renderConversion();if(to==='g'&&!Number.isInteger(result))toast('Swapped using the nearest whole gram.');};
function renderIngredients(){const q=$('ingredient-search').value.trim().toLowerCase(),matches=INGREDIENTS.filter(i=>(i.name+' '+i.aliases).toLowerCase().includes(q));const list=$('ingredient-list');list.replaceChildren();if(!matches.length){const p=document.createElement('p');p.className='help';p.textContent='No ingredients found. Try another name, such as flour or sugar.';list.append(p);}for(const i of matches){const b=document.createElement('button');b.className='ingredient-item';b.setAttribute('aria-pressed',String(i.id===state.ingredient));const strong=document.createElement('strong'),small=document.createElement('small');strong.textContent=i.name;small.textContent=i.aliases||i.reference;b.append(strong,small);b.onclick=()=>{state.ingredient=i.id;$('ingredient-dialog').close();renderConversion();};list.append(b);}}
// Keep the picker inside the visible screen, including when iOS opens its keyboard.
function fitIngredientPicker(){
 const picker=$('ingredient-dialog'),viewport=window.visualViewport;
 const visibleHeight=viewport?.height||window.innerHeight,offset=viewport?.offsetTop||0;
 const height=Math.min(720,Math.max(0,visibleHeight-16));
 picker.style.setProperty('--picker-height',`${height}px`);
 picker.style.setProperty('--picker-top',`${offset+visibleHeight-height-8}px`);
}
function updateOpenPicker(){if($('ingredient-dialog').open)fitIngredientPicker();}
window.visualViewport?.addEventListener('resize',updateOpenPicker);
window.visualViewport?.addEventListener('scroll',updateOpenPicker);
window.addEventListener('resize',updateOpenPicker);
$('ingredient-btn').onclick=()=>{
 $('ingredient-search').value='';renderIngredients();fitIngredientPicker();showDialog('ingredient-dialog');
 // Focus a non-editable control so browsing never summons the software keyboard.
 $('ingredient-dialog').querySelector('[data-close]').focus({preventScroll:true});
 $('ingredient-list').scrollTop=0;
};
$('ingredient-search').oninput=()=>{renderIngredients();$('ingredient-list').scrollTop=0;};
function references(single=false){
 $('reference-title').textContent=single?ingredient(state.ingredient).name:'Our measures';const body=$('reference-body');body.replaceChildren();
 if(!single){body.innerHTML='<p>Grams are entered and displayed as whole numbers. Kilograms, cups and other units retain useful decimal precision.</p><p>We use a US customary cup (236.588 mL), US tablespoons and teaspoons, plus separate metric measures: 250 mL cups, 15 mL tablespoons and 5 mL teaspoons. Australian 20 mL tablespoons are not included.</p><p>Ingredient weights are kitchen references, not exact densities for every brand. Spoon and level flour, pack brown sugar, and use level measuring spoons. Prefer the gram weights in your recipe.</p><p><a href="https://www.nist.gov/pml/owm/metric-si/metric-kitchen" target="_blank" rel="noopener noreferrer">NIST measurement guidance</a></p>';}
 const selected=single?[ingredient(state.ingredient)]:INGREDIENTS;
 for(const i of selected){const card=document.createElement('div');card.className='card';const title=document.createElement('h3'),ref=document.createElement('p'),note=document.createElement('p'),link=document.createElement('a');title.textContent=i.name;ref.textContent=i.reference;note.textContent=i.note;note.className='help';link.href=i.source;link.textContent=i.sourceName;link.target='_blank';link.rel='noopener noreferrer';card.append(title,ref,note,link);body.append(card);}showDialog('reference-dialog');
}
$('reference-btn').onclick=()=>references();$('ingredient-reference').onclick=()=>references(true);
const input=(id,label,value,{grams=false}={})=>`<label for="${id}">${label}</label><input id="${id}" class="field" type="text" inputmode="${grams?'numeric':'decimal'}" value="${value}" ${grams?'data-grams':''} autocomplete="off">`;
const line=(label,value)=>`<div class="result-line"><span>${label}</span><strong>${value}</strong></div>`;
const read=(id,opts={})=>number($(id).value,opts);
const grams=(id,label)=>read(id,{whole:true,label});
function toolShell(name){$('tool-grid').hidden=true;$('tool-panel').hidden=false;$('tools-title').textContent=name;$('tool-panel').innerHTML='<button id="back-tools" class="text-btn">← All baking tools</button><div id="tool-content"></div>';$('back-tools').onclick=()=>{$('tool-grid').hidden=false;$('tool-panel').hidden=true;$('tools-title').textContent='Baking tools';};}
function hydration(){toolShell('Hydration');renderHydration();}
function renderHydration(){const build=state.mode==='build';$('tool-content').innerHTML=`<div class="segmented" aria-label="Hydration mode"><button id="build-mode" aria-pressed="${build}">Build by target</button><button id="analyse-mode" aria-pressed="${!build}">Check my dough</button></div><label class="check-label"><input id="sourdough" type="checkbox" ${state.sourdough?'checked':''}> Include sourdough starter</label><div class="card">${input('h-flour',build?'Total flour, including starter (g)':'Flour you add (g)',build?1000:500,{grams:true})}${build?input('h-hydration','Target hydration (%)',70):input('h-water','Water you add (g)',350,{grams:true})}<div id="starter-fields" ${state.sourdough?'':'hidden'}>${input('h-starter','Starter you add (g)',100,{grams:true})}${input('h-starter-hydration','Starter hydration (%)',100)}<p class="help">100% starter hydration means equal weights of flour and water.</p></div>${build?input('h-salt-percent','Salt (% of total flour)',2):input('h-salt','Salt you add (g)',10,{grams:true})}<p class="help">Hydration is total water ÷ total flour, including both parts of the starter. This tool covers flour-and-water doughs; milk and eggs need a separate water-content calculation.</p></div><p id="h-error" class="error" role="alert" hidden></p><div id="h-result" class="card" aria-live="polite"></div>`;
 $('build-mode').onclick=()=>{state.mode='build';renderHydration();};$('analyse-mode').onclick=()=>{state.mode='analyse';renderHydration();};$('sourdough').onchange=()=>{state.sourdough=$('sourdough').checked;$('starter-fields').hidden=!state.sourdough;calculateHydration();};
 bindGramInputs($('tool-content'));for(const i of $('tool-content').querySelectorAll('input:not([type=checkbox])'))i.addEventListener('input',calculateHydration);calculateHydration();}
function calculateHydration(){try{const starter=state.sourdough?grams('h-starter','Starter'):0,sh=state.sourdough?read('h-starter-hydration',{label:'Starter hydration'}):100,flour=grams('h-flour','Flour');
 if(state.mode==='build'){const target=read('h-hydration',{label:'Hydration'}),r=buildDough(flour,target,starter,sh,read('h-salt-percent',{label:'Salt percentage'}));const rounded={flour:Math.round(r.flour),water:Math.round(r.water),salt:Math.round(r.salt)};
 let note='';if(rounded.flour+starter/(1+sh/100)>0){const actual=analyseDough(rounded.flour,rounded.water,starter,sh,rounded.salt);note=`Using the whole-gram quantities gives ${decimal(actual.hydration,4)}% hydration.`;}
 $('h-result').innerHTML=`<p class="eyebrow">Add to your bowl</p>${line('Flour',measured(r.flour))}${line('Water',measured(r.water))}${state.sourdough?line('Starter',measured(starter)):''}${line('Salt',measured(r.salt))}<p class="help">${note} Yeast quantity and fermentation time depend on your recipe.</p>`;
 }else{const r=analyseDough(flour,grams('h-water','Water'),starter,sh,grams('h-salt','Salt'));$('h-result').innerHTML=`<p class="eyebrow">Your dough hydration</p><p class="hero-number">${decimal(r.hydration,4)}%</p>${line('Total flour',measured(r.totalFlour))}${line('Total water',measured(r.totalWater))}${line('Salt percentage',decimal(r.saltPercent,4)+'%')}<p class="help">Flour and water in the starter are included. Gram summaries are rounded; hydration uses unrounded totals.</p>`;}
 errorAt('h-error','');$('h-result').hidden=false;
 }catch(e){errorAt('h-error',e.message);$('h-result').hidden=true;}}
function pan(){toolShell('Pan sizes');const fields=(prefix,title,a)=>`<fieldset class="card"><legend>${title}</legend><label for="${prefix}-shape">Shape</label><select id="${prefix}-shape" class="field"><option value="round">Round</option><option value="square">Square</option><option value="rectangle">Rectangle</option></select><label for="${prefix}-unit">Dimension unit</label><select id="${prefix}-unit" class="field"><option value="in">Inches</option><option value="cm">Centimetres</option></select>${input(prefix+'-a','Diameter',a)}<div id="${prefix}-width" hidden>${input(prefix+'-b','Width',7)}</div></fieldset>`;$('tool-content').innerHTML=fields('pan-from','Original tin',7)+fields('pan-to','New tin',8)+'<p id="pan-error" class="error" role="alert" hidden></p><div id="pan-result" class="card" aria-live="polite"></div><p class="help">For tins of similar depth, this keeps the batter at the same height. Use internal dimensions. Leave enough space for rising. Baking time does not scale by this factor; check doneness.</p>';
 const calc=()=>{try{const pans=['pan-from','pan-to'].map(p=>{const shape=$(p+'-shape').value;$(p+'-width').hidden=shape!=='rectangle';document.querySelector(`label[for="${p}-a"]`).textContent=shape==='round'?'Diameter':shape==='square'?'Side length':'Length';return{shape,unit:$(p+'-unit').value,a:read(p+'-a',{positive:true,label:'Pan size'}),b:shape==='rectangle'?read(p+'-b',{positive:true,label:'Pan width'}):1};});const factor=panScale(...pans);$('pan-result').innerHTML=`<p class="eyebrow">Multiply every ingredient by</p><p class="hero-number">${decimal(factor,5)}×</p>${line('For 100 g in the original recipe',measured(100*factor))}<button id="pan-to-scale" class="btn secondary">Use this factor in Recipe scale</button>`;$('pan-to-scale').onclick=()=>scale(factor);$('pan-result').hidden=false;errorAt('pan-error','');}catch(e){errorAt('pan-error',e.message);$('pan-result').hidden=true;}};for(const e of $('tool-content').querySelectorAll('input,select'))e.addEventListener('input',calc);calc();}
let scaleRows=[{name:'Flour',amount:'250',unit:'g'},{name:'Water',amount:'175',unit:'g'},{name:'Salt',amount:'5',unit:'g'}];
function scale(factor=2){toolShell('Recipe scale');$('tool-content').innerHTML=`<div class="card">${input('scale-factor','Multiply the recipe by',decimal(factor,12))}<p class="help">Use 2 to double, 0.5 to halve, or enter any positive factor.</p><div id="scale-rows"></div><button id="add-scale-row" class="text-btn">+ Add ingredient</button><p id="scale-error" class="error" role="alert" hidden></p></div><button id="save-scaled" class="btn">Save scaled recipe</button><p class="help">Gram results are rounded to whole grams. Other units keep decimals. For eggs, weigh the beaten egg and enter its weight in grams.</p>`;
 $('add-scale-row').onclick=()=>{captureScale();scaleRows.push({name:'',amount:'',unit:'g'});renderScaleRows();};$('scale-factor').oninput=calculateScale;$('save-scaled').onclick=()=>{const results=calculateScale();if(results){openEditor({name:'Scaled recipe',notes:results.map(r=>`${measured(r.value,r.unit)} ${r.name||'Ingredient'}`).join('\n')});}};renderScaleRows();}
function captureScale(){scaleRows=Array.from(document.querySelectorAll('.scale-row')).map(row=>({name:row.querySelector('.scale-name').value,amount:row.querySelector('.scale-amount').value,unit:row.querySelector('.scale-unit').value}));}
function renderScaleRows(){const rows=$('scale-rows');rows.replaceChildren();scaleRows.forEach((r,i)=>{const div=document.createElement('div');div.className='scale-row';div.innerHTML=`<label for="scale-name-${i}">Ingredient ${i+1}</label><input class="field scale-name" id="scale-name-${i}" placeholder="Ingredient name" maxlength="150"><div class="two"><div><label for="scale-amount-${i}">Original amount</label><input class="field scale-amount" id="scale-amount-${i}" type="text"></div><div><label for="scale-unit-${i}">Unit</label><select class="field scale-unit" id="scale-unit-${i}">${unitOptions(r.unit)}</select></div></div><div class="scale-bottom"><output class="scale-output" aria-live="polite"></output><button class="text-btn danger" aria-label="Remove ingredient ${i+1}">Remove</button></div>`;div.querySelector('.scale-name').value=r.name;const a=div.querySelector('.scale-amount');a.value=r.amount;a.inputMode=r.unit==='g'?'numeric':'decimal';div.querySelector('button').onclick=()=>{captureScale();scaleRows.splice(i,1);renderScaleRows();};div.addEventListener('input',()=>{a.inputMode=div.querySelector('.scale-unit').value==='g'?'numeric':'decimal';calculateScale();});a.addEventListener('blur',()=>{if(div.querySelector('.scale-unit').value==='g')normaliseGrams(a);calculateScale();});div.querySelector('.scale-unit').addEventListener('change',()=>{if(div.querySelector('.scale-unit').value==='g')normaliseGrams(a);calculateScale();});rows.append(div);});calculateScale();}
function calculateScale(){try{captureScale();const factor=read('scale-factor',{positive:true,label:'Scale factor'});if(!scaleRows.length)throw Error('Add at least one ingredient.');const result=scaleRows.map(r=>({...r,value:scaleAmount(number(r.amount,{whole:r.unit==='g',label:r.name||'Ingredient amount'}),factor)}));for(const [i,row]of Array.from(document.querySelectorAll('.scale-row')).entries())row.querySelector('output').textContent='→ '+measured(result[i].value,result[i].unit);errorAt('scale-error','');return result;}catch(e){errorAt('scale-error',e.message);for(const out of document.querySelectorAll('.scale-output'))out.textContent='—';return null;}}
function ovenTool(){toolShell('Oven');$('tool-content').innerHTML=`<div class="card">${input('oven-amount','Conventional oven temperature',180)}<label for="oven-unit">Input unit</label><select id="oven-unit" class="field"><option value="c">Celsius (°C)</option><option value="f">Fahrenheit (°F)</option></select></div><p id="oven-error" class="error" role="alert" hidden></p><div id="oven-result" class="card" aria-live="polite"></div><p class="help">Fan guidance is approximate: about 20°C lower than conventional. Follow the recipe or oven manufacturer's instructions. Fahrenheit conversion itself uses the exact formula.</p>`;const calc=()=>{try{const n=read('oven-amount',{label:'Temperature'}),u=$('oven-unit').value,c=u==='c'?n:oven(n,'f');if(c<30||c>350)throw Error('Enter a baking temperature from 30°C to 350°C (86°F to 662°F).');$('oven-result').innerHTML=`<p class="eyebrow">Equivalent conventional temperature</p><p class="hero-number">${decimal(oven(n,u),5)}°${u==='c'?'F':'C'}</p>${line('Approximate fan setting',`${Math.round(c-20)}°C / ${Math.round(oven(c-20,'c'))}°F`)}`;errorAt('oven-error','');$('oven-result').hidden=false;}catch(e){errorAt('oven-error',e.message);$('oven-result').hidden=true;}};for(const e of $('tool-content').querySelectorAll('input,select'))e.addEventListener('input',calc);calc();}
for(const b of document.querySelectorAll('[data-tool]'))b.onclick=()=>({hydration,pan,scale:()=>scale(),oven:ovenTool}[b.dataset.tool]());
async function refreshRecipes(){state.recipes=await getRecipes();renderRecipes();}
function releaseListURLs(){listURLs.forEach(URL.revokeObjectURL);listURLs=[];}
function renderRecipes(){releaseListURLs();const q=$('recipe-search').value.trim().toLowerCase(),rows=state.recipes.filter(r=>(r.name+' '+r.notes+' '+r.category).toLowerCase().includes(q)).sort((a,b)=>b.updated-a.updated);const list=$('recipe-list');list.replaceChildren();if(!rows.length){const box=document.createElement('div');box.className='empty';box.innerHTML=q?'<h3>No matching recipes</h3><p>Try another name, ingredient or note.</p>':'<h3>Your notebook starts here</h3><p>Add a recipe photo or write your own notes.</p><button id="empty-add" class="btn secondary">Add your first recipe</button>';list.append(box);if(!q)$('empty-add').onclick=()=>openEditor();return;}
 for(const r of rows){const b=document.createElement('button');b.className='recipe-card';if(r.photo instanceof Blob){const im=document.createElement('img');im.src=URL.createObjectURL(r.photo);listURLs.push(im.src);im.alt='';b.append(im);}else{const ph=document.createElement('span');ph.className='recipe-placeholder';ph.textContent='▤';ph.setAttribute('aria-hidden','true');b.append(ph);}const content=document.createElement('span'),name=document.createElement('strong'),meta=document.createElement('small');name.textContent=r.name;meta.textContent=`${r.category||'Other'} · ${new Date(r.updated).toLocaleDateString()}`;content.append(name,meta);b.append(content);b.onclick=()=>showRecipe(r.id);list.append(b);}}
function updatePreview(){if(previewURL)URL.revokeObjectURL(previewURL);previewURL=null;const image=$('recipe-photo-preview');image.hidden=!state.photo;$('remove-photo').hidden=!state.photo;if(state.photo){previewURL=URL.createObjectURL(state.photo);image.src=previewURL;}else image.removeAttribute('src');}
function openEditor(seed=null){state.editing=seed?.id||null;state.photo=seed?.photo||null;$('recipe-dialog-title').textContent=state.editing?'Edit recipe':'New recipe';$('recipe-name').value=seed?.name||'';$('recipe-category').value=seed?.category||'Bread';$('recipe-notes').value=seed?.notes||'';errorAt('recipe-error','');updatePreview();showDialog('recipe-dialog');$('recipe-name').focus();}
$('add-recipe').onclick=()=>openEditor();$('recipe-search').oninput=renderRecipes;
async function resizePhoto(file){if(file.size>20*1024*1024)throw Error('Choose a photo smaller than 20 MB.');if(!file.type.startsWith('image/'))throw Error('Choose an image file.');const url=URL.createObjectURL(file);try{const im=new Image();im.src=url;await new Promise((resolve,reject)=>{im.onload=resolve;im.onerror=()=>reject(Error('This image could not be opened. Try a JPEG or PNG.'));});const ratio=Math.min(1,1800/Math.max(im.width,im.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(im.width*ratio));canvas.height=Math.max(1,Math.round(im.height*ratio));const ctx=canvas.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(im,0,0,canvas.width,canvas.height);return await new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('Photo could not be prepared.')),'image/jpeg',.9));}finally{URL.revokeObjectURL(url);}}
for(const id of ['camera-file','photo-file'])$(id).onchange=async e=>{const file=e.target.files[0];if(!file)return;$('save-recipe').disabled=true;try{state.photo=await resizePhoto(file);updatePreview();errorAt('recipe-error','');}catch(err){errorAt('recipe-error',err.message);}finally{$('save-recipe').disabled=false;e.target.value='';}};
$('take-photo').onclick=()=>$('camera-file').click();$('choose-photo').onclick=()=>$('photo-file').click();$('remove-photo').onclick=()=>{state.photo=null;updatePreview();};
$('recipe-form').onsubmit=async e=>{e.preventDefault();const name=$('recipe-name').value.trim();if(!name){errorAt('recipe-error','Give your recipe a name.');return;}const old=state.recipes.find(r=>r.id===state.editing);const recipe={id:state.editing||crypto.randomUUID(),name,category:$('recipe-category').value,notes:$('recipe-notes').value,photo:state.photo,created:old?.created||Date.now(),updated:Date.now()};$('save-recipe').disabled=true;try{await putRecipe(recipe);await refreshRecipes();$('recipe-dialog').close();switchView('recipes');toast('Recipe saved on this device.');}catch{errorAt('recipe-error','The recipe could not be saved. Your draft is still here. Free some device space or check browser storage permissions, then try again.');}finally{$('save-recipe').disabled=false;}};
function showRecipe(id){const r=state.recipes.find(r=>r.id===id);if(!r)return;state.detail=id;$('detail-title').textContent=r.name;$('detail-meta').textContent=r.category||'Other';$('detail-notes').textContent=r.notes||'No notes added.';if(detailURL)URL.revokeObjectURL(detailURL);detailURL=null;$('detail-photo').hidden=!r.photo;if(r.photo){detailURL=URL.createObjectURL(r.photo);$('detail-photo').src=detailURL;}else $('detail-photo').removeAttribute('src');showDialog('detail-dialog');}
$('edit-recipe').onclick=()=>{const r=state.recipes.find(r=>r.id===state.detail);$('detail-dialog').close();openEditor(r);};
$('delete-recipe').onclick=()=>{$('confirm-name').textContent=state.recipes.find(r=>r.id===state.detail)?.name||'';showDialog('confirm-dialog');};$('cancel-delete').onclick=()=>$('confirm-dialog').close();
$('confirm-delete').onclick=async()=>{const b=$('confirm-delete');b.disabled=true;try{await deleteRecipe(state.detail);$('confirm-dialog').close();$('detail-dialog').close();await refreshRecipes();toast('Recipe deleted from this device.');}catch{toast('Recipe could not be deleted. Please try again.');}finally{b.disabled=false;}};
function blobData(blob){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(reader.error);reader.readAsDataURL(blob);});}
$('export-recipes').onclick=async()=>{const b=$('export-recipes');b.disabled=true;try{const recipes=await getRecipes();if(!recipes.length){toast('There are no recipes to back up yet.');return;}const rows=await Promise.all(recipes.map(async r=>({...r,photo:r.photo?await blobData(r.photo):null})));const blob=new Blob([JSON.stringify({format:'baker-calculator-recipes',version:1,created:new Date().toISOString(),recipes:rows})],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`Baker-Recipes-${new Date().toISOString().slice(0,10)}.json`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);toast('Backup prepared. Keep the downloaded file somewhere safe.');}catch{toast('Backup could not be created. Please try again.');}finally{b.disabled=false;}};
$('import-recipes').onclick=()=>$('backup-file').click();$('backup-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>50*1024*1024)throw Error('Choose a backup smaller than 50 MB.');const rows=validateBackup(JSON.parse(await file.text()));await importRecipes(rows);await refreshRecipes();toast(`${rows.length} recipes restored as copies. Existing recipes were kept.`);}catch(err){toast(err instanceof SyntaxError?'This file is not a valid recipe backup.':err.message||'Backup could not be restored.');}finally{e.target.value='';}};
async function init(){renderConversion();try{const r=await migrate(ingredient);await refreshRecipes();$('storage-status').textContent=r.issues.length?r.issues.join(' '):r.count?`${r.count} older recipes recovered on this device.`:'';}catch{$('storage-status').textContent='Recipe storage is unavailable. Calculators still work; check your browser storage settings before saving recipes.';renderRecipes();}
 if('serviceWorker' in navigator&&location.protocol!=='file:'){try{await navigator.serviceWorker.register('./sw.js');await navigator.serviceWorker.ready;$('offline-status').textContent=navigator.onLine?'Available offline after this visit':'Offline · calculations stay on this device';}catch{$('offline-status').textContent='Offline reopening unavailable in this browser';}}
}
window.addEventListener('online',()=>{$('offline-status').textContent='Online';});window.addEventListener('offline',()=>{$('offline-status').textContent='Offline · calculations stay on this device';});
init();
