import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {JSDOM} from 'jsdom';
import {indexedDB,IDBKeyRange} from 'fake-indexeddb';
import {UNITS,US_CUP,number,convert,decimal,amountText,practical,buildDough,analyseDough,panScale,oven,scaleAmount} from '../math.mjs';
import {ingredient,INGREDIENTS} from '../ingredients.mjs';
let passed=0;
function test(name,fn){try{fn();passed++;console.log('PASS',name);}catch(e){console.error('FAIL',name);throw e;}}
const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-9*Math.max(1,Math.abs(b)),`${a} != ${b}`);
test('Known unit conversions and density references',()=>{
 close(convert(1,'g','kg',ingredient('water')),.001);close(convert(1,'lb','g',ingredient('water')),453.59237);
 close(convert(1,'oz','g',ingredient('water')),28.349523125);
 close(convert(1,'cup','tbsp'),16);close(convert(1,'tbsp','tsp'),3);close(convert(1,'metric_cup','ml'),250);
 close(convert(1,'cup','g',ingredient('all_purpose_flour')),120);close(convert(100,'g','cup',ingredient('all_purpose_flour')),5/6);
 close(convert(1,'tsp','g',ingredient('fine_salt')),6);close(convert(1,'tsp','g',ingredient('baking_powder')),4);
 close(convert(100,'ml','g',ingredient('whole_milk')),103);close(convert(180,'ml','g',ingredient('greek_yogurt')),170);
});
test('Whole grams and nonzero small-unit output',()=>{assert.equal(number('123',{whole:true}),123);assert.throws(()=>number('123.45',{whole:true}));assert.equal(amountText(.001,'kg'),'0.001');assert.equal(amountText(.1,'g'),'<1');assert.equal(amountText(123.45,'g'),'123');assert.equal(number('0,5'),.5);for(const v of ['', '-1','Infinity','1e309','NaN','1/2','1000000001'])assert.throws(()=>number(v));});
test('US and metric practical measures',()=>{assert.equal(practical(convert(100,'g','ml',ingredient('all_purpose_flour'))),'¾ US cup + 1 tbsp + 1 tsp');assert.equal(practical(US_CUP/48),'1 tsp');assert.equal(practical(250,true),'1 metric cup');assert.equal(practical(.0001),'< ⅛ US tsp');assert.equal(practical(0),'0');});
test('Sourdough includes starter flour and water',()=>{const a=analyseDough(500,350,100,100,10);close(a.hydration,400/550*100);close(a.totalFlour,550);close(a.totalWater,400);const b=buildDough(1000,70,200,100,2);assert.deepEqual(b,{flour:900,water:600,starter:200,salt:20});const stiff=buildDough(1000,70,150,50,2);close(stiff.flour,900);close(stiff.water,650);assert.throws(()=>buildDough(100,10,200,100,2));assert.throws(()=>analyseDough(0,100));});
test('Pan conversion uses area and mixed units',()=>{const a={shape:'round',a:7,unit:'in'},b={shape:'round',a:8,unit:'in'};close(panScale(a,b),64/49);close(panScale(b,a),49/64);close(panScale({shape:'square',a:8,unit:'in'},{shape:'square',a:20.32,unit:'cm'}),1);close(panScale({shape:'rectangle',a:20,b:30,unit:'cm'},{shape:'square',a:20,unit:'cm'}),2/3);assert.throws(()=>panScale({shape:'round',a:0},b));});
test('Scaling and oven equations',()=>{close(scaleAmount(250,1.5),375);close(scaleAmount(375,2/3),250);close(oven(180,'c'),356);close(oven(350,'f'),176.66666666666666);assert.throws(()=>scaleAmount(10,0));});
let rounds=0;test('All ingredient/unit round trips preserve numerical precision',()=>{for(const i of INGREDIENTS)for(const a of Object.keys(UNITS))for(const b of Object.keys(UNITS))for(const value of [.001,1,100,1000]){const out=convert(value,a,b,i);close(convert(out,b,a,i),value);rounds++;}});
const html=await readFile(new URL('../index.html',import.meta.url),'utf8');const dom=new JSDOM(html,{url:'https://example.test/baker-calculator-test/'});const w=dom.window;
Object.assign(globalThis,{window:w,document:w.document,localStorage:w.localStorage,indexedDB,IDBKeyRange,Image:w.Image});Object.defineProperty(globalThis,'navigator',{value:w.navigator,configurable:true});Object.defineProperty(globalThis,'location',{value:w.location,configurable:true});w.scrollTo=()=>{};
w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};
const sourcePhoto=new Blob([Uint8Array.from([1,2,3])],{type:'image/png'});
const old=await new Promise((resolve,reject)=>{const r=indexedDB.open('BakerCalculatorDB',1);r.onupgradeneeded=()=>r.result.createObjectStore('photos');r.onsuccess=()=>resolve(r.result);r.onerror=reject;});
await new Promise((resolve,reject)=>{const tx=old.transaction('photos','readwrite');tx.objectStore('photos').put(sourcePhoto,'old-1');tx.oncomplete=resolve;tx.onerror=reject;});old.close();
localStorage.setItem('bcFreshRecipes',JSON.stringify([{id:101,n:'Recent bread',notes:'line one\nline two',photo:'data:image/png;base64,AQID'}]));
localStorage.setItem('bcRecipeLibraryV1',JSON.stringify([{id:'old-1',name:'Earlier bread',notes:'Keep notes',hasPhoto:true,ingredients:[{ingredient:'all_purpose_flour',grams:250}],created:100}]));
const storage=await import('../storage.mjs');
const migrated=await storage.migrate(ingredient);test('Both legacy formats and IndexedDB photos migrate',()=>{assert.equal(migrated.count,2);assert.deepEqual(migrated.issues,[]);assert.ok(localStorage.getItem('bcFreshRecipes'));assert.ok(localStorage.getItem('bcRecipeLibraryV1'));});
let saved=await storage.getRecipes();test('Migrated notes and photo bytes survive',()=>{const old=saved.find(r=>r.name==='Earlier bread');assert.match(old.notes,/250 g Plain flour/);assert.match(old.notes,/Keep notes/);assert.equal(old.photo.size,3);assert.equal(saved.find(r=>r.name==='Recent bread').photo.size,3);});
await storage.deleteRecipe(saved[0].id);await storage.migrate(ingredient);saved=await storage.getRecipes();test('Deleted migrated recipes do not reappear',()=>assert.equal(saved.length,1));
const bad=[{format:'wrong',version:1,recipes:[]},{format:'baker-calculator-recipes',version:1,recipes:[{id:'x',name:'',notes:''}]}];test('Invalid backups rejected before writes',()=>bad.forEach(x=>assert.throws(()=>storage.validateBackup(x))));
const backup=storage.validateBackup({format:'baker-calculator-recipes',version:1,recipes:[{id:'x',name:'Restore test',notes:'A\nB',photo:'data:image/png;base64,AQID'}]});await storage.importRecipes(backup);saved=await storage.getRecipes();test('Backup restores notes and photos without overwriting',()=>{assert.equal(saved.length,2);assert.equal(saved.find(r=>r.name==='Restore test').photo.size,3);});
const viewport=new w.EventTarget();viewport.height=800;viewport.offsetTop=0;Object.defineProperty(w,'visualViewport',{value:viewport,configurable:true});
await import('../app.mjs');
const $=id=>document.getElementById(id);const input=(id,value,type='input')=>{$(id).value=value;$(id).dispatchEvent(new w.Event(type,{bubbles:true}));};
await new Promise(r=>setTimeout(r,30));
test('Whole-gram paste is normalised; kg keeps 0.001',()=>{input('amount','123.45');assert.equal($('result').textContent,'—');$('amount').dispatchEvent(new w.Event('blur'));assert.equal($('amount').value,'123');input('amount','1');input('to-unit','kg','change');assert.equal($('result').textContent,'0.001');input('amount','');assert.equal($('result').textContent,'—');assert.equal($('convert-error').hidden,false);input('amount','-10');assert.equal($('result').textContent,'—');input('amount','100');});
test('Ingredient picker avoids keyboard autofocus and fits the visible screen',()=>{
 $('ingredient-btn').click();
 assert.equal($('ingredient-search').hasAttribute('autofocus'),false);
 assert.equal(document.activeElement,$('ingredient-dialog').querySelector('[data-close]'));
 const fits=()=>{const sheet=$('ingredient-dialog');const top=parseFloat(sheet.style.getPropertyValue('--picker-top')),height=parseFloat(sheet.style.getPropertyValue('--picker-height'));assert.ok(top>=viewport.offsetTop);assert.ok(top+height<=viewport.offsetTop+viewport.height-8);};
 fits();viewport.height=340;viewport.offsetTop=70;viewport.dispatchEvent(new w.Event('resize'));fits();
 viewport.offsetTop=110;viewport.dispatchEvent(new w.Event('scroll'));fits();
 viewport.height=800;viewport.offsetTop=0;viewport.dispatchEvent(new w.Event('resize'));fits();
 $('ingredient-list').querySelector('button:last-child').click();assert.equal($('ingredient-dialog').open,false);
 $('ingredient-dialog').close();
});
test('Ingredient alias search and empty feedback',()=>{$('ingredient-btn').click();input('ingredient-search','powdered');assert.equal($('ingredient-list').querySelectorAll('button').length,1);assert.match($('ingredient-list').textContent,/Icing sugar/);input('ingredient-search','notpresent');assert.match($('ingredient-list').textContent,/No ingredients/);$('ingredient-dialog').close();});
test('Hydration interface calculates and rejects impossible targets',()=>{document.querySelector('[data-tool=hydration]').click();assert.match($('h-result').textContent,/700 g/);$('sourdough').checked=true;$('sourdough').dispatchEvent(new w.Event('change'));input('h-starter','200');assert.match($('h-result').textContent,/600 g/);input('h-starter','10000');assert.equal($('h-result').hidden,true);assert.match($('h-error').textContent,/more flour or water/);$('analyse-mode').click();assert.match($('h-result').textContent,/72.73%/);});
test('Pan, scale and oven interfaces work',()=>{$('back-tools').click();document.querySelector('[data-tool=pan]').click();assert.match($('pan-result').textContent,/1.3061/);input('pan-from-a','0');assert.equal($('pan-result').hidden,true);input('pan-from-a','7');$('pan-to-scale').click();assert.match(document.querySelector('.scale-output').textContent,/327 g/);input('scale-factor','0');assert.equal($('scale-error').hidden,false);$('back-tools').click();document.querySelector('[data-tool=oven]').click();assert.match($('oven-result').textContent,/356°F/);});
$('add-recipe').click();input('recipe-name','<img src=x onerror=alert(1)>');input('recipe-notes','First line\nSecond line <b>literal</b>');$('recipe-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await new Promise(r=>setTimeout(r,30));
test('Saved user text stays literal and line breaks survive',()=>{assert.equal($('recipe-list').querySelectorAll('img[src=x]').length,0);assert.ok($('recipe-list').textContent.includes('<img src=x'));const b=[...$('recipe-list').querySelectorAll('button')].find(b=>b.textContent.includes('<img src=x'));b.click();assert.equal($('detail-notes').textContent,'First line\nSecond line <b>literal</b>');assert.equal($('detail-notes').querySelector('b'),null);});
$('edit-recipe').click();input('recipe-name','Edited recipe');$('recipe-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await new Promise(r=>setTimeout(r,30));
test('Editing updates the saved recipe',()=>{assert.match($('recipe-list').textContent,/Edited recipe/);assert.ok(!$('recipe-list').textContent.includes('<img src=x'));});
const edited=[...$('recipe-list').querySelectorAll('button')].find(b=>b.textContent.includes('Edited recipe'));edited.click();$('delete-recipe').click();$('confirm-delete').click();await new Promise(r=>setTimeout(r,30));
test('Confirmed deletion updates the recipe list',()=>assert.ok(!$('recipe-list').textContent.includes('Edited recipe')));
test('Navigation has three clearly labelled destinations',()=>assert.deepEqual([...document.querySelectorAll('nav button span')].map(e=>e.textContent),['Convert','Tools','Recipes']));
console.log(`\n${passed} test groups passed; ${rounds} round-trip calculation cases.`);
w.close();
